language: node_js
services: mongodb
addons:
  code_climate:
    repo_token: 32d255d79fc556e0b47516b1172b39b4b1d07ed8aed2217bb24e86a283a9dce0
node_js: 7
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn coverage
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: aleksander.ginovski@gmail.com
  api_key:
    secure: PmiJs8z3szBVcl4/Xtjco1nciyqJMcIFRRmSZpn9DGSd9ivB+s3kCKpw3rs7QuMEWj7a9wCSWX42FncnQbhAzziRJHYPd4+a3Bj+B8xgEvDIKTg1xKWfvhP5XtuGp5fCBdInyIKDEJ2ZaRbk72UgFZ0esw3qJ/dFsJWsFUR6OrvIGaFfLr0WgFYAvK7sCTJJJf39LNT1F1ETzQbVpcFuAEiGAeM/7m36Drep5+zYuduWMC4fs/7JlcmoEgB+dmxaVkF+Vb1z3hMxeeLwfIpqPHitvI0V1f4nCtlb/l44c98lJUP16GMLniEPUa3ipm0sV5Iz6qydvfbxfr8l7kWB016ShHsCSGA9zenA9feg4/8vX/g9dUutTxU8V67W8i4gIkRJ/UemkoVMZFelyOQpy1Iw7uBTxAO8Ug2mns+FNwuKgD5zjn2fa58uxq8R07BQR52/lVgEJhAoElGOMvxCwFVul/n10GL3bjlnRUKVvog1qtzpwaA10OpOatRmNIoM9r0EOos6Rz+0GewFm5Bik76IZmCQq/djrFjMFg0qgVnt1gg8LOqRJ4zKDhw27xmKLDpOaogcLCLD5io/XGdMMf/Fy5SsjdT6hPwK3y3pOw1E2+MBVCtbfshlWJChLqSDb7MdecvyWP42JtUOZ+MCO0RbawNpvH4uRYWeY31J2tc=
  on:
    tags: true
    repo: enhancv/mongoose-subscriptions-braintree
notifications:
  email: false
  slack:
    secure: Q61hQyFwTuDewv58RCELl6gNiO29VJQBkwOFGw0Jjj5iQOd2bIiY4eX1gvtduHel3fYnlglMyIOpmGL5a7uOPJMLjJ2SRCzlzEHe4Yhf+dqXPnfoBtzUSrzWc3boFXs3pvJOxz6SMWKpDnqjwYcgJu+MqQf4tesMPnk0msMWN+j8oIDLueE195P5wfgmnXLaDKkz7SJOYp9iSbhtGh5Bs5EKJfORuq32TWNnNtLsdHVTs1h2D6WjO5z72eeHjFISX2Zpt+dCow8zeyuI5ABXCkMUZsbn1LUdFX5fV9tUgueOv8KZfQkI34VP+jj+IyNQq1K3ylva60jVY+dDJ6z5JwKN7ArV0Elwhikn5Bcs4EDCpL8mwViSmHf1QEg77RwUDgFC4WfvsbfpF2aRqS82BPp0O2x2DjRFsLxcudMLVDI3klj8ClTZG1vLz0Tkbwxh8Uky5j2KqcZOcKt7/l1ZJOv6/NfHfxhW+1f9yOxPUzioBELWn6BBNVL5ULwbPbyFBsrlpC+e3W6kD1j+B6a79txJ7QutKWgQT4DyJweUim6J1ZZ8EWobwp0MWaM2kIxXPp+4KGHYV08dLvTaLht0/7Nt4JymYz/cruAeKha8ascxmcvcejHMdH01JTAeoZwvhvJ92sm2WzO2p4UWGUZQTs0rNettT6SmuWQaU8Y0nXk=
