language: node_js
services: mongodb
node_js: 6
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn run coverage
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
